name: Urban BB
favicon: null
layout_spectrum: 0.25383
typography_spectrum: 0.5392265063710511
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#21242d'
    - '#cecbbc'
    - '#2694bb'
    - '#eb887d'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.5941428509540856
  rhythmicContrast: 0.5774208812508732
purpose: []
